language: java

notifications:
  slack:
    secure: FIHlTn/YO7Wgumm1uIqmoEsqjQA7fV0AE94Rjc5yKzM3AquQa8HicgDVVk0d2GrKRnl0xt3j4ZJV//VJyIjlCd/QVKuj48R2ChjEY2im3+99HFPafCUI5/S2uyowKU6mJTFonH9v6p41eqxdbiAxJdDGOT0V2Gpt3UBSNuHz8ED9/aIHqv+P7M+VD6Xd2XYwctPniWlaSWx57sWcnG/VkFG45qFQAyha64uxOOe4M3ZmG/n5FfauZ8cBVLiRKEIr+CyNhh1ujfzi7+4uzMlSNL5t/BbZamAQuZzqGzGQ9RVvIlyPgUGNJtDEE/hWS09aagXF5T6EMj00szizErh4J1/x4qZwml5+TcBN31E0QmAhCtZe85sr3tYgic+hEz9XX1yymQzf/C7n4to2yNvq0r4g51xDk8IuP95WEh7zaqLlvFZvBFgxpHZBMYlRvhytjOYDeIFRMcGwHZcXosaG2ejqDwcGq/LC4oeG4sSwmg9sdRrtcmcanrNqrBka86WYO6LntI3JdZ86/1ACEUHzhCCwvrKELc9Ji1xxGAgS7QKH+s2/hnJuiMyv73gOVLKYC+wPMLt+fvOmPLSEl+PJiAIlToBq1KUBg03RSQLfPOLD7OrJ8VvDZsEPwejqlGDyc4wRglS9OTi7SnN5LYHSDNDdGdREegWqq9qDHEYEVLI=

env:
  # Fill out these global variables for build process
  matrix:
    - ENGINE=lucee@5
    - ENGINE=adobe@2016
    - ENGINE=adobe@2018

branches:
  only:
  - development
  - master

sudo: required
dist: xenial

before_install:
# CommandBox Keys
  - curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
  - sudo echo "deb https://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a
    /etc/apt/sources.list.d/commandbox.list

install:
  # Install Commandbox
  - sudo apt-get update && sudo apt-get --assume-yes install jq commandbox
  # Install CommandBox Supporting Librarires
  - box install commandbox-cfconfig,commandbox-dotenv
  # If using auto-publish, you will need to provide your API token with this line:
  - box config set endpoints.forgebox.APIToken=$FORGEBOX_API_TOKEN > /dev/null

script:
  # Set Current Version and Travis Tag
  - TARGET_VERSION=`cat $TRAVIS_BUILD_DIR/box.json | jq '.version' -r`
  - TRAVIS_TAG=${TARGET_VERSION}
  - echo "Starting build for DocBox v${TARGET_VERSION}"
  # Replace version so builder can issue it
  - box package set version=@build.version@+@build.number@
  # run our dependency install to ensure the workbench is in place
  - box install
  # run our matrix server
  - box server start serverConfigFile="server-${ENGINE}.json"
  # Build Project
  - box task run taskfile=build/Build target=run :version=${TARGET_VERSION} :buildID=${TRAVIS_BUILD_NUMBER} :branch=${TRAVIS_BRANCH}

after_failure:
  - cd $TRAVIS_BUILD_DIR
  # Display the contents of our root directory
  # Spit out our Commandbox log in case we need to debug
  - box server log server-${ENGINE}.json
  - cat `box system-log`

deploy:
  # Binary Deployments
  - provider: s3
    on:
      branch:
        - master
        - development
      #condition: "$ENGINE = lucee@4.5"
    skip_cleanup: true
    #AWS Credentials need to be set in Travis
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: "downloads.ortussolutions.com"
    local-dir: $TRAVIS_BUILD_DIR/.artifacts/docbox
    upload-dir: ortussolutions/docbox
    acl: public_read

  #API Docs Deployment
  - provider: s3
    on:
      branch:
        - master
        - development
      #condition: "$ENGINE = lucee@4.5"
    skip_cleanup: true
    #AWS Credentials need to be set in Travis
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: "apidocs.ortussolutions.com"
    local-dir: $TRAVIS_BUILD_DIR/tests/apidocs
    upload-dir: docbox/$BUILD_VERSION
    acl: public_read

  # Github Release only on Master
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    on:
      branch:
        - master
      condition: "$ENGINE = lucee@5"
    skip_cleanup: true
    edge: true
    file_glob: true
    file: $TRAVIS_BUILD_DIR/.artifacts/docbox/**/*
    release_notes_file: $TRAVIS_BUILD_DIR/changelog-latest.md
    name: v${TRAVIS_TAG}
    tag_name: v${TRAVIS_TAG}
    overwrite: true

after_deploy:
  # Move to build out artifact
  - cd ${TRAVIS_BUILD_DIR}/.tmp/docbox
  - cat box.json
  # Only publish once using the lucee matrix
  - if [ ${ENGINE} = 'lucee@5' ]; then box forgebox publish; fi
